/**
 * Mapping rules for the brand generator (Playbook Step 9/10).
 *
 * Scope decision: a brand is defined here as a re-supply of CORE tier raw values
 * (color ramps, radius scale, spacing scale, font families). Semantic and base tiers
 * — and every headless component — are structural and stay byte-identical between
 * base and brand, which is what lets "supplying a new set of values" retheme the
 * whole system without touching components. Anything a Figma file provides that
 * doesn't cleanly resolve to one of these core slots is surfaced as "unmapped"
 * rather than guessed.
 */

export const COLOR_ROLE_RULES = [
  {
    role: 'brand',
    corePath: 'color.brand',
    keywords: ['brand', 'primary'],
    description: 'Primary brand ramp — drives action.primary.*, color.primary.*, focus ring, links.',
  },
  {
    role: 'secondary',
    corePath: 'color.secondary',
    keywords: ['secondary', 'accent'],
    description: 'Secondary/accent ramp — supporting actions. Falls back to the brand ramp if the base system has no dedicated secondary core palette.',
  },
  {
    role: 'neutral',
    corePath: 'color.neutral',
    keywords: ['neutral', 'gray', 'grey'],
    description: 'Neutral ramp — surfaces, borders, body text, disabled states.',
  },
  {
    role: 'success',
    corePath: 'color.green',
    keywords: ['success', 'green', 'positive'],
    description: 'Success feedback color.',
  },
  {
    role: 'error',
    corePath: 'color.red',
    keywords: ['error', 'red', 'danger', 'destructive'],
    description: 'Error / destructive feedback color.',
  },
  {
    role: 'warning',
    corePath: 'color.orange',
    keywords: ['warning', 'orange', 'caution'],
    description: 'Warning feedback color.',
  },
  {
    role: 'info',
    corePath: 'color.blue',
    keywords: ['info', 'blue', 'link'],
    description: 'Informational / link color.',
  },
];

// Matches the step keys used in tokens/core/color.json.
export const COLOR_RAMP_STEPS = ['0', '50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950', '1000'];

// The step every solo/anchor color (when a bucket has only one Figma value) is assumed to represent.
export const COLOR_RAMP_ANCHOR_STEP = '500';

// Matches tokens/core/radius.json.
export const RADIUS_SCALE_KEYS = ['none', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', 'full'];

// Matches tokens/core/spacing.json.
export const SPACING_SCALE_KEYS = ['none', '3xs', '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl'];

// Matches tokens/core/typography.json -> font.family.*
export const FONT_FAMILY_SLOT_RULES = [
  { slot: 'monospace', keywords: ['mono', 'code'] },
  { slot: 'display', keywords: ['display', 'heading', 'hero'] },
  { slot: 'secondary', keywords: ['secondary'] },
  { slot: 'primary', keywords: ['primary', 'body', 'default', 'ui'] },
];

export const MAPPING_RULES_DOC = `Base BNTS DS — Figma-to-base-parameter mapping rules

1. COLORS
   Each Figma color style/variable is bucketed by keyword match against its name
   (case-insensitive substring): brand/primary, secondary/accent, neutral/gray,
   success/green, error/red/danger, warning/orange, info/blue/link.
   - If a bucket receives a full 13-step ramp (steps: ${COLOR_RAMP_STEPS.join(', ')}),
     each step is used directly — confidence "high".
   - If a bucket receives a single color, it is treated as the "500" anchor and the
     rest of the ramp is generated by HSL lightness interpolation — confidence
     "medium", every interpolated step flagged needsReview: true.
   - Colors that don't match any keyword bucket are listed as unmapped; they are
     never silently discarded or guessed into a bucket.

2. RADIUS
   Figma radius values are sorted ascending and assigned in order to the base scale
   keys (${RADIUS_SCALE_KEYS.join(', ')}). An exact count match is "high" confidence;
   a mismatched count is "medium" confidence and flagged for manual confirmation.

3. SPACING
   Same approach as radius, against (${SPACING_SCALE_KEYS.join(', ')}).

4. TYPOGRAPHY
   Figma type styles are matched by name to a font-family slot (primary, secondary,
   display, monospace) and only the raw font-family string is carried into core.
   The semantic type scale (sizes/weights/line-heights per role) is left untouched
   by design — the base's modular scale is treated as house style, not a per-brand
   variable, unless a human explicitly overrides it after review.

5. NEVER INVENT
   Anything that cannot be matched with the rules above is returned as "unmapped"
   with the raw Figma data attached, so a human (or the requesting AI) must decide
   — it is never silently defaulted to a guessed value.`;
